# Generated by Django 5.0.7 on 2024-07-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_type_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='categoria',
            field=models.ManyToManyField(to='erp.categoria'),
        ),
    ]
